spring:
  datasource:
    url: jdbc:mysql://localhost:3306/menudb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: menu
    password: menu

mybatis:
  mapper-locations: classpath:resources/mapper/*.xml
  config-location: classpath:mapper/mapper-config.xml